services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    image: bitnami/php-fpm:8.2
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html

  db:
    image: bitnami/mysql:latest
    container_name: db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=connection_check
      - MYSQL_USER=sqluser
      - MYSQL_PASSWORD=sqlpassword123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
